name: CI
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  '25 23 */3 * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2
        submodules: true
    - name: Guix cache
      if: ${{ ! steps.guix_pack_cache.outputs.cache-hit }}
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/guix
        key: guix-cache
        restore-keys: |
          guix-cache
    - name: Install Guix
      id: install-guix
      uses: TxGVNN/guix-install-action@v1
      with:
        channels: |-
            (list (channel
                   (name 'guxti)
                   (branch "master")
                   (commit "c7fa485fd2a352bb6baaa21f749073be7b05204f")
                   (url "https://github.com/TxGVNN/guxti")
                   (introduction
                    (make-channel-introduction
                     "34ce27aeadde4ab8b26802453628f713155c0e96"
                     (openpgp-fingerprint
                      "97EE 7685 F353 F3BB AAFC  D3DA 8D6C 190A CBFE 117C"))))
                  (channel
                   (name 'guix)
                   (branch "master")
                   (url "https://codeberg.org/guix/guix.git")
                   (introduction
                    (make-channel-introduction
                     "9edb3f66fd807b096b48283debdcddccfea34bad"
                     (openpgp-fingerprint
                      "BBB0 2DDF 2CEA F6A8 0D1D  E643 A2A0 6DF2 A33A 54FA")))))

    - name: Install packages
      shell: bash
      run: |
        guix package -m manifest.scm
    - name: Build Emacs Lisp Package Archive
      shell: bash
      run: |
        . ~/.guix-profile/etc/profile
        mkdir -p ~/.emacs.d
        cp early-init.el ~/.emacs.d/
        export elpa_mirror_dir=$(find ~/.guix-profile/share/ -name elpa-mirror\*)
        emacs --batch -nw -l ${elpa_mirror_dir}/elpa-mirror-autoloads.el --eval '(elpamr-create-mirror-for-installed "packages")'
    - name: Publish packages
      run: |
        cd packages
        ls -l | awk '{print "<li><a href=\""$9"\">"$9"</a></li>"}' > index.html
        git init --initial-branch=packages
        cp ../.git/config .git/
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "Build packages"
        git push --force origin packages
