name: CI
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ guix ]
  pull_request:
    branches: [ guix ]
  workflow_run:
    workflows:
      - Trigger
    types:
      - completed
  schedule:
    - cron:  '25 23 */3 * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2
        submodules: true
    - name: Install Guix
      id: install-guix
      uses: PromyLOPh/guix-install-action@v1
      with:
        channels: |-
            (list (channel
                   (name 'guix)
                   (commit "ef0613a")
                   (url "https://git.savannah.gnu.org/git/guix.git"))
                  (channel
                   (name 'guxti)
                   (url "https://github.com/TxGVNN/guxti")))
    - name: Install packages
      shell: bash
      run: |
        guix package -m manifest.scm
    - name: Build Emacs Lisp Package Archive
      shell: bash
      run: |
        emacs --batch -nw -l ~/.guix-profile/share/emacs/site-lisp/elpa-mirror-2.2.0-20230115/elpa-mirror-autoloads.el --eval '(elpamr-create-mirror-for-installed "packages")'
    - name: Publish packages
      run: |
        cd packages
        ls -l | awk '{print "<li><a href=\""$9"\">"$9"</a></li>"}' > index.html
        git init --initial-branch=packages
        cp ../.git/config .git/
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "Build packages"
        git push --force origin packages
