name: CI
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ guix ]
  pull_request:
    branches: [ guix ]
  workflow_run:
    workflows:
      - Trigger
    types:
      - completed
  schedule:
    - cron:  '25 23 */3 * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2
        submodules: true
    - name: Install Guix
      id: install-guix
      uses: PromyLOPh/guix-install-action@v1
      with:
        channels: |-
            (list (channel
                   (name 'guix)
                   (commit "ef0613a")
                   (url "https://git.savannah.gnu.org/git/guix.git"))
                  (channel
                   (name 'guxti)
                   (url "https://github.com/TxGVNN/guxti")))
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
