name: CI
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_run:
    workflows:
      - Trigger
    types:
      - completed
  schedule:
    - cron:  '25 23 */3 * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
        submodules: true
    - name: Install dependencies
      run: |
        sudo apt-get install emacs25
        sudo apt-get install git jq mercurial texinfo

        # Work around SSL-related failures, see
        # https://stackoverflow.com/questions/21477683/mercurial-https-clone-abort-error-wrong-version-number
        echo "[ui]\ntls = False" > $HOME/.hgrc

    - name: Rebuild packages html
      run: |
        make packages packages/archive-contents

    - name: Publish package html
      run: |
        cd packages
        ls -l | awk '{print "<li><a href=\""$9"\">"$9"</a></li>"}' > index.html
        git init --initial-branch=packages
        cp ../.git/config .git/
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "Build packages"
        git push --force origin packages
