name: ci
on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
        submodules: true
    - name: Install dependencies
      run: |
        sudo apt-get install emacs25
        sudo apt-get install git jq mercurial texinfo

        # Work around SSL-related failures, see
        # https://stackoverflow.com/questions/21477683/mercurial-https-clone-abort-error-wrong-version-number
        echo "[ui]\ntls = False" > $HOME/.hgrc

        # Use cask to install development dependencies
        curl -fsSkL https://raw.github.com/cask/cask/master/go | python
    - name: Run cask
      run: |
        ~/.cask/bin/cask
    - name: Rebuild packages html
      run: |
        make packages packages/archive-contents

    - name: Publish package html
      run: |
        pushd packages
        git checkout -b packages
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "Generate packages"
        git push origin packages
        # Update submodule
        popd
        git add -u
        git commit -m 'Update packages'
        git push origin master
